# Generated by Django 5.2.10 on 2026-01-26 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teammember",
            name="account_number",
        ),
        migrations.RemoveField(
            model_name="teammember",
            name="bank_name",
        ),
        migrations.RemoveField(
            model_name="teammember",
            name="hourly_rate",
        ),
        migrations.RemoveField(
            model_name="teammember",
            name="ifsc_code",
        ),
        migrations.AddField(
            model_name="teammember",
            name="daily_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="id_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="teammember",
            name="mpesa_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="teammember",
            name="mpesa_number",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="phone",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
