# Generated by Django on...
from django.db import migrations
from django.contrib.auth.models import User

def create_superuser(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    
    # Check if superuser already exists
    if not User.objects.filter(is_superuser=True).exists():
        user = User.objects.create_superuser(
            username='admin',
            email='testadmin@gmail.com',
            password='admin123'
        )
        user.first_name = 'admin'
        user.last_name = 'test'
        user.save()

def reverse_func(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    User.objects.filter(username='admin').delete()

class Migration(migrations.Migration):
    dependencies = [
        # Add your dependencies here
        ('teams', '0002_remove_teammember_account_number_and_more'), 
    ]

    operations = [
        migrations.RunPython(create_superuser, reverse_func),
    ]