# Generated by Django 5.2.11 on 2026-03-04 16:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0003_create_superuser"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teammember",
            old_name="daily_rate",
            new_name="shift_rate",
        ),
    ]
