# Generated by Django 5.2.10 on 2026-01-26 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="hourly_rate",
            new_name="daily_rate",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="total_hours",
        ),
        migrations.AddField(
            model_name="invoice",
            name="mpesa_confirmation_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="mpesa_transaction_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="number_of_days",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("mpesa", "M-Pesa"),
                    ("cash", "Cash"),
                    ("bank", "Bank Transfer"),
                ],
                default="mpesa",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="eventreport",
            name="report_content",
            field=models.TextField(blank=True),
        ),
    ]
