# Generated by Django 5.2.11 on 2026-03-04 16:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0002_rename_hourly_rate_invoice_daily_rate_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="daily_rate",
            new_name="shift_rate",
        ),
    ]
